### ISSUE TITLE
Enable prompt broadcasting / specification

### ISSUE THREAD

**Issue by Blair-Johnson** [Blair-Johnson/batch-whisper#3]
Currently prompt specification of the form `model.transcribe([audio1, audio2], prompt='prompt')` is untested. Need to investigate and enable the following usage: `model.transcribe([audio1, audio2], prompt=['prompt1', 'prompt2'])`, and `model.transcribe([audio1, audio2], prompt='prompt')` (where `'prompt'` is used for all input files).
# TODO
- [ ] Investigate current behavior when prompts are specified by the user
- [ ] Enable per-file prompt specification
- [ ] Enable broadcast prompt specification

**Comment by shaynemei** [comment]
@Blair-Johnson Hi, this would be a great feature. Is this being worked on?

**Comment by Blair-Johnson** [comment]
> @Blair-Johnson Hi, this would be a great feature. Is this being worked on?

Thanks for your interest! I currently don't have a timeline for implementing prompting, but it is on the to-do list for when I have more bandwidth to work on this.
